server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
              - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackurl: forward:/userServiceFallBack
        - id: DEPT-SERVICE
          uri: lb://DEPT-SERVICE
          predicates:
              - Path=/depts/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPT-SERVICE
                fallbackurl: forward:/deptServiceFallBack
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost